### PR TITLE
Add specs for passing nested objects correctly to the api, #24

### PR DESCRIPTION
**Pull request by ad1992**
Thanks for quickly merging https://github.com/CharlesMangwa/react-data-fetching/pull/25. I was just writing spec for the pr, but it got merged before I could push the commit, hence opening a new PR.

### CODE REVIEW

**Comment by CharlesMangwa** [comment]
No worries @ad1992, thanks for following up with the tests! 🙌 Can I merge now (I rater ask to be sure this time 😅)?

**Comment by ad1992** [comment]
sure @CharlesMangwa please go ahead and merge :) and also a version bump :)

**Comment by CharlesMangwa** [comment]
I'm working on the next major version that should come soon (I hope), so this fix will be included in it =)

**Comment by ad1992** [comment]
@CharlesMangwa if possible would be great if you could do a minor version bump so that I can use the library in my project.

**Comment by CharlesMangwa** [comment]
@ad1992 👋!
The fix is now available under [`v0.2.3`](https://www.npmjs.com/package/react-data-fetching/v/0.2.3) on npm, thanks for your patience!

**Pull request merged**
